FROM node:16-alpine as build
# Set the working directory within the container
WORKDIR /app
COPY package.json .
RUN yarn install
COPY . .
ENV VITE_REACT_API_URL=https://cms-api-staging.seven-gen.com
ENV VITE_REACT_SECRET=
RUN yarn shadcn-ui init
RUN yarn build 

# runner
FROM nginx:1.21-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/nginx-staging.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]