export const SET_AUTHENTICATION = 'SET_AUTHENTICATION'

export const SET_COUNTER_ON_SSE_OPEN = 'SET_COUNTER_ON_SSE_OPEN';

export const SET_DEVICE_LIST = 'SET_DEVICE_LIST';
export const SET_DEVICE_INFO = 'SET_DEVICE_INFO';